package routes

import (
	"github.com/gin-gonic/gin"
	admincontroller "github.com/rafa/golang-cc/internal/controllers/admin"
	servermw "github.com/rafa/golang-cc/internal/server/middleware"
)

func RegisterAdmin(engine *gin.Engine, c *admincontroller.Controller, authService servermw.Authenticator) {
	admin := engine.Group("/api/admin", servermw.Authentication(authService), servermw.Role(servermw.ADMIN))
	admin.GET("/invitings", c.ListInvitings)
	admin.GET("/dashboard", c.Dashboard)
	admin.GET("/users", c.ListUsers)
	admin.GET("/telegram-bindings", c.ListTelegramBindings)
	admin.GET("/banks", c.ListBanks)
	admin.GET("/networks", c.ListNetworks)
	admin.GET("/card-products", c.ListCards)
	admin.GET("/card-products/:id", c.GetCardProduct)
	admin.GET("/activities", c.ListActivities)
	admin.GET("/activities/:id", c.GetActivity)
	admin.GET("/requirement-types", c.ListRequirementTypes)
	admin.GET("/activity-requirement-options", c.ActivityRequirementOptions)
	admin.GET("/regions", c.ListRegions)
	admin.GET("/user-qualifications", c.ListUserQualifications)
	admin.GET("/categories", c.ListCategories)
	admin.GET("/reward-units", c.ListRewardUnits)
	admin.GET("/payment-methods", c.ListPaymentMethods)
	admin.GET("/merchants", c.ListMerchants)

	write := admin.Group("", servermw.CSRF())
	write.POST("/invitations", c.CreateInvitation)
	write.DELETE("/invitations/:id", c.DeleteInvitation)
	write.POST("/users/:id/password-reset", c.SendUserPasswordReset)
	write.POST("/telegram-bindings", c.CreateTelegramBinding)
	write.DELETE("/telegram-bindings/:chat_id", c.DeleteTelegramBinding)
	write.PATCH("/users/:id", c.UpdateUserStatus)
	write.POST("/banks", c.CreateBank)
	write.PATCH("/banks/:id", c.UpdateBank)
	write.DELETE("/banks/:id", c.DeleteBank)
	write.POST("/card-products", c.CreateCardProduct)
	write.PATCH("/card-products/:id", c.UpdateCard)
	write.DELETE("/card-products/:id", c.DeleteCard)
	write.POST("/activities", c.CreateActivity)
	write.PUT("/activities/:id", c.UpdateActivity)
	write.PATCH("/activities/:id/status", c.SetActivityStatus)
	write.DELETE("/activities/:id", c.DeleteActivity)
	write.POST("/regions", c.CreateRegion)
	write.PATCH("/regions/:id", c.UpdateRegion)
	write.DELETE("/regions/:id", c.DeleteRegion)
	write.POST("/user-qualifications", c.CreateUserQualification)
	write.PATCH("/user-qualifications/:id", c.UpdateUserQualification)
	write.DELETE("/user-qualifications/:id", c.DeleteUserQualification)
	write.POST("/categories", c.CreateCategory)
	write.PATCH("/categories/:id", c.UpdateCategory)
	write.DELETE("/categories/:id", c.DeleteCategory)
	write.POST("/reward-units", c.CreateRewardUnit)
	write.PATCH("/reward-units/:id", c.UpdateRewardUnit)
	write.DELETE("/reward-units/:id", c.DeleteRewardUnit)
	write.POST("/payment-methods", c.CreatePaymentMethod)
	write.PATCH("/payment-methods/:id", c.UpdatePaymentMethod)
	write.DELETE("/payment-methods/:id", c.DeletePaymentMethod)
	write.POST("/merchants", c.CreateMerchant)
	write.PATCH("/merchants/:id", c.UpdateMerchant)
	write.DELETE("/merchants/:id", c.DeleteMerchant)
	write.POST("/reward-components/:componentId/versions", c.PublishComponentVersion)
	write.POST("/reward-conditions/:conditionId/versions", c.PublishConditionVersion)
	write.POST("/reward-caps/:capId/versions", c.PublishCapVersion)
}
