DROP TABLE IF EXISTS member_profile.reward_usage_adjustments;
DROP TABLE IF EXISTS integration.outbox_events;
ALTER TABLE transactions DROP COLUMN IF EXISTS status;
ALTER TABLE transactions DROP COLUMN IF EXISTS channel;
ALTER TABLE transactions DROP COLUMN IF EXISTS country_code;
ALTER TABLE transactions DROP COLUMN IF EXISTS currency_code;
ALTER TABLE transactions DROP COLUMN IF EXISTS card_network_id;
DROP TABLE IF EXISTS "transaction".reward_calculation_components;
DROP TABLE IF EXISTS "transaction".reward_calculations;
DROP TABLE IF EXISTS reward.component_caps;
DROP TABLE IF EXISTS reward.cap_versions;
DROP TABLE IF EXISTS reward.caps;
DROP TABLE IF EXISTS reward.requirements;
DROP TABLE IF EXISTS reward.condition_versions;
DROP TABLE IF EXISTS reward.conditions;
DROP TABLE IF EXISTS reward.component_versions;
DROP TABLE IF EXISTS reward.components;
DROP TABLE IF EXISTS reward.programs;
DROP TABLE IF EXISTS member_profile.user_payment_methods;
ALTER TABLE payment_methods DROP CONSTRAINT IF EXISTS payment_methods_type_check;
ALTER TABLE payment_methods DROP COLUMN IF EXISTS display_order;
ALTER TABLE payment_methods DROP COLUMN IF EXISTS type;
DROP TABLE IF EXISTS catalog.member_card_qualification_statuses;
DROP TABLE IF EXISTS catalog.card_plan_versions;
DROP TABLE IF EXISTS catalog.card_plans;
DROP TRIGGER IF EXISTS member_card_network_check ON member_cards;
DROP FUNCTION IF EXISTS catalog.validate_member_card_network();
DROP INDEX IF EXISTS member_cards_user_product_network_uidx;
ALTER TABLE member_cards DROP COLUMN IF EXISTS closed_on;
ALTER TABLE member_cards DROP COLUMN IF EXISTS opened_on;
ALTER TABLE member_cards DROP COLUMN IF EXISTS card_network_id;
DROP TABLE IF EXISTS catalog.card_product_networks;
DROP TABLE IF EXISTS catalog.card_networks;
ALTER TABLE card_products DROP COLUMN IF EXISTS is_open_for_application;
ALTER TABLE card_products DROP COLUMN IF EXISTS primary_color;
ALTER TABLE card_products DROP COLUMN IF EXISTS card_image_url;
ALTER TABLE card_products DROP COLUMN IF EXISTS description;
ALTER TABLE card_products DROP COLUMN IF EXISTS code;
ALTER TABLE banks DROP COLUMN IF EXISTS logo_url;
DROP SCHEMA IF EXISTS integration;
DROP SCHEMA IF EXISTS "transaction";
DROP SCHEMA IF EXISTS recommendation;
DROP SCHEMA IF EXISTS member_profile;
DROP SCHEMA IF EXISTS reward;
DROP SCHEMA IF EXISTS merchant;
DROP SCHEMA IF EXISTS catalog;
DROP SCHEMA IF EXISTS identity;
